### PR TITLE
Joystick component

### LINKED ISSUE #9: Implement ability to move in all cardinal directions
As a user, I would like to be able to control the car myself, so that I am the one issuing the commands to move.

Acceptance Criteria:
Ability to move the car manually (forwards, backwards, left, right) with the GUI. Car does not move spontaneously.

### LINKED ISSUE #11: Implement CI/CD pipeline
Implement CI/CD pipeline for continuous integration and delivery.

### LINKED ISSUE #15: Interface Skeleton
As a developer I need a skeleton for the GUI where I can implement the necessary features such as Valet Mode, Cruise Control etc.

### PR DESCRIPTION
**Pull request by nk-io**
Joystick component added.
Some refactoring and improvement.
Bugfix related to Arduino CI

Closes #9 
Closes #11
Closes #15

### CODE REVIEW

**Review by gsastraw — APPROVED** [review]
Very nice!! The message pollution in the joystick is still a problem, I'll make an issue to highlight this.

**Review by JensTheS — APPROVED** [review]
Looks good.
During a team meeting we had a brief discussion about the prints to the console.
They will be kept.

**Comment by JensTheS** [comment]
The branch #20 was integrated here and should therefore be closed when this merges to master.
Closes #20

**Comment by gsastraw** [comment]
Created an issue to highlight the message pollution issue:

See #22

**Pull request merged**
