### PR TITLE
Login screen

### PR DESCRIPTION
**Pull request by gsastraw**
Need to add user authentication to login screen

### CODE REVIEW

**Comment by ktpa** [comment]
The login screen looks nice, but the loop itself should not be as apparent as it is right now. It depends on what level of polish we're aiming for, but I would say that an opacity shift in at the start and end is one way to solve it without using clever filmmaking tricks.

It is however, kind of dangerous to merge this into the security layer in this state because the joystick seems to not be initialized in a proper manner due to the fact that this error is crashing the program when you use it:
```

E/InputEventReceiver: Exception dispatching input event.

E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback

E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke interface method 
'void group01.smartcar.client.JoystickView$JoystickListener.onJoystickMoved(float, float, int)' on a null object reference

```

Steps to reproduce:
1. Login to the software using any the button.
2. Attempt to move the joystick.

On further inspection, it also seems like the other listeners are broken in this PR. I'm on the hunt.

**Review by ktpa — CHANGES_REQUESTED** [review]
JoystickView constructors (rows 34, 43, 50) doesn't properly set up the joystick listener causing the software to crash. These should be changed to point to our joystick. We also lost our debug log when using the start and stop buttons.

**Comment by ktpa** [comment]
> 
> 
> JoystickView constructors (rows 34, 43, 50) doesn't properly set up the joystick listener causing the software to crash. These should be changed to point to our joystick. We also lost our debug log when using the start and stop buttons.

This wasn't wrong per-say, but the real issue was changing screens without using the intent.

**Review by ktpa — APPROVED** [review]

**Comment by gsastraw** [comment]
Looks good! There is still an ongoing issue with the MQTT connection (#22) where not all messages are received. The UI will also be polished in the future!

**Pull request merged**
