### PR TITLE
Develop

### LINKED ISSUE #60: Persistence Layer
As a user of AlSet, I would like to save personalized settings of my car such as driving sensitivity so that I have a consistent driving experience.

**Acceptance Criteria**
The user must have all settings saved to a database when logging out. Upon logging back in, these settings must be exactly how it was when they left it.

### PR DESCRIPTION
**Pull request by ktpa**
Merging the improved joystick to master.

### CODE REVIEW

**Comment by nk-io** [comment]
This PR includes a refactored version of voice recognition functionality.

Closes #43 
Closes #44

**Comment by gsastraw** [comment]
Closes #59 #60

**Comment by gsastraw** [comment]
Misclicked, sorry, this pull request closes #59 #60

**Comment by ktpa** [comment]
Attempting to exit out of the app back to title screen yields a NullPointerException. Should be fixed before any approving can be done.

**Review by gsastraw — APPROVED** [review]

**Pull request merged**
